export const BasictestData = [
    {
        rank: 1,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 2,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 3,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 4,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 5,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 6,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 7,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 8,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 9,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
    {
        rank: 10,
        name: 'Selling with re entr',
        Calmar_Ratio: 3.96,
        overall_Profit: 6464684,
        Avg_Daily_Profit: 319.58,
        Win_Day: 0.68,
        Price: 100 ,
        action: 'view',
    },
];
